"""
Generate cmg_datafile/rock_fluid_properties_varying_v2_30.inc
with 30 rock types (RPT 1 - RPT 30) using Brooks-Corey model.

Same TOTAL parameter change as generate_relperm_varying.py, but split into
30 rock types (29 steps) instead of 10 (9 steps):

RPT 1  : original BC-fitted parameters
RPT 2-30 : linear variation of two parameters across the 29 steps:
    S_wc / S_lr   (connate water / liquid sat) : 0.13 -> 0.03  (-0.10 total)
    k_ep          (endpoint kr: k_rw_max = k_rog_max) : 0.35 -> 0.60  (+0.25 total)

All other BC parameters are held fixed at the RPT-1 fitted values:
    S_or = S_gr = 0.20
    k_row_max = k_rg_max = 1.0
    n_w = n_l = 3.5 ,  n_o = n_g = 1.5
    P_e = 0.3837 ,  lam = 1.5447

Gas-liquid table uses SGT (indexed by Sg, increasing from 0 to Sg_max = 1 - S_lr).
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from read_relperm import parse_relperm
from fit_brooks_corey import fit_swt, fit_sgt
from generate_relperm_varying import _write_rpt

# ── Constants ─────────────────────────────────────────────────────────────────

N_RPT = 30          # total number of rock types (v2: 30 instead of 10)

# Total parameter change identical to the 10-RPT version:
S_WC_START, S_WC_END = 0.13, 0.03   # S_wc / S_lr : -0.10 total
K_EP_START, K_EP_END = 0.35, 0.60   # k_rw_max = k_rog_max : +0.25 total


# ── Parameter variation across RPTs ──────────────────────────────────────────

def make_rpt_params(p_swt_base, p_sgt_base):
    """
    Generate parameter dicts for all N_RPT rock types.

    Linear interpolation from RPT 1 (n=0) to RPT 30 (n=29):
      S_wc / S_lr  : 0.13  -> 0.03   (frac * 0.10 decrease)
      k_ep         : 0.35  -> 0.60   (frac * 0.25 increase)
    """
    rpts = []
    for n in range(N_RPT):
        frac   = n / (N_RPT - 1)    # 0.0 at RPT 1,  1.0 at RPT 30
        S_wc_n = S_WC_START + frac * (S_WC_END - S_WC_START)
        k_ep_n = K_EP_START + frac * (K_EP_END - K_EP_START)

        p_swt_n = dict(p_swt_base)
        p_swt_n["S_wc"]     = S_wc_n
        p_swt_n["k_rw_max"] = k_ep_n

        p_sgt_n = dict(p_sgt_base)
        p_sgt_n["S_lr"]      = S_wc_n
        p_sgt_n["k_rog_max"] = k_ep_n

        rpts.append((p_swt_n, p_sgt_n))
    return rpts


# ── Main ──────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    # Load original table and fit BC parameters
    swt, sgt = parse_relperm("cmg_datafile/rock_fluid_properties.inc")
    p_swt_base = fit_swt(swt)
    p_sgt_base = fit_sgt(sgt)

    # Build parameter set for all 30 RPTs
    rpt_params = make_rpt_params(p_swt_base, p_sgt_base)

    # Print summary table
    print(f"{'RPT':>4}  {'S_wc/S_lr':>12}  {'k_ep (k_rw_max=k_rog_max)':>26}")
    print("-" * 48)
    for i, (ps, pg) in enumerate(rpt_params):
        print(f"{i+1:>4}  {ps['S_wc']:>12.4f}  {ps['k_rw_max']:>26.4f}")

    # Write CMG .inc file
    out_path = os.path.join("cmg_datafile", "rock_fluid_properties_varying_v2_30.inc")
    with open(out_path, "w") as fh:
        fh.write("** Rock-fluid properties with varying endpoint kr and residual saturation\n")
        fh.write("** RPT 1 : original BC-fitted curve\n")
        fh.write("** RPT 2-30 : S_wc/S_lr 0.13->0.03, k_rw_max/k_rog_max 0.35->0.60\n")
        fh.write("** Same total change as the 10-RPT version, split into 30 rock types\n")
        fh.write("** Generated by generate_relperm_varying_v2_spilit_in_30.py\n")

        for i, (ps, pg) in enumerate(rpt_params):
            _write_rpt(fh, i + 1, ps, pg)

    print(f"\nWrote: {out_path}")
